'use client';

import { useState } from 'react';

interface FAQItem {
  question: string;
  answer: string;
}

const faqData: FAQItem[] = [
  {
    question: 'What is Smart Otter?',
    answer:
      'Smart Otter is an AI-powered resource discovery platform. Enter any profession or technical domain (e.g., "Frontend Developer", "Quantum Computing Researcher") and it returns curated recommendations for tools, communities, learning platforms, and documentation — generated by large language models.',
  },
  {
    question: 'How does Smart Otter generate resources?',
    answer:
      'Smart Otter sends your search query to an AI model (Groq Cloud or a local Ollama instance) with a structured system prompt asking for categorized resource recommendations. The response is parsed into four categories — Tools, Communities, Learning Platforms, and Documentation — each containing the resource name, URL, and a brief explanation of why it is relevant.',
  },
  {
    question: 'What happens when I search for a profession that has already been searched?',
    answer:
      'Results are cached in PostgreSQL with a 24-hour time-to-live. If another user (or you) searches the same profession within that window, Smart Otter returns the cached results instantly without calling an AI provider.',
  },
  {
    question: 'Why does Smart Otter use multiple AI providers?',
    answer:
      'Smart Otter defaults to Groq Cloud as its primary provider but falls back to a local Ollama instance if Groq is unavailable. This ensures search continues working even when one provider experiences downtime or rate limits. You can select your preferred provider in Developer Mode.',
  },
  {
    question: 'What is Developer Mode?',
    answer:
      'Developer Mode is available only in development (`NODE_ENV === "development"`). Click the gear icon next to your avatar to open a side panel where you can select your active AI provider (Groq Cloud, Ollama Local, or Auto/Hybrid), view live status indicators for each provider, and manage the knowledge cache.',
  },
  {
    question: 'Are the resources guaranteed to be correct?',
    answer:
      'No. Resources are generated by large language models and may contain inaccuracies — incorrect URLs, outdated recommendations, or fabricated entries. Always verify links and recommendations before relying on them. Smart Otter is a discovery aid, not a curated directory.',
  },
  {
    question: 'Is Smart Otter free?',
    answer:
      'Yes. Smart Otter is an open-source project released under the MIT license. There are no plans for paid tiers or monetization at this time.',
  },
  {
    question: 'Can I suggest a resource to be added?',
    answer:
      'Not currently. Smart Otter generates all recommendations via AI and does not yet support user-submitted resources. This feature may be considered in a future release.',
  },
];

export default function FAQPage() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const toggle = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <div className="max-w-3xl mx-auto px-6 py-12">
      <h1 className="text-3xl font-bold tracking-tight mb-2">Frequently Asked Questions</h1>
      <p className="text-muted-foreground mb-10">
        Installation, updates, troubleshooting, and the questions newcomers ask first.
      </p>

      <div className="space-y-3" role="list">
        {faqData.map((item, index) => (
          <div key={index} className="border border-border rounded-lg overflow-hidden">
            <button
              type="button"
              onClick={() => toggle(index)}
              aria-expanded={openIndex === index}
              aria-controls={`faq-answer-${index}`}
              id={`faq-question-${index}`}
              className="flex items-center justify-between w-full px-5 py-4 text-left font-medium text-sm hover:bg-muted/50 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"
            >
              <span>{item.question}</span>
              <svg
                className="size-4 shrink-0 text-muted-foreground transition-transform duration-200"
                style={{ transform: openIndex === index ? 'rotate(180deg)' : 'rotate(0deg)' }}
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <polyline points="6 9 12 15 18 9" />
              </svg>
            </button>

            {openIndex === index && (
              <div
                id={`faq-answer-${index}`}
                role="region"
                className="px-5 pb-4 text-sm text-muted-foreground leading-relaxed"
              >
                {item.answer}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
